name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js for activities-data
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'

    - name: Install dependencies for activities-data
      run: |
        npm install

    - name: Compile TypeScript for activities-data
      run: |
        npm run build  # Assuming you have a build script in your package.json that runs `tsc`

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push activities-data image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dip-sharing-board-activities-data:latest -f Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/dip-sharing-board-activities-data:latest
